# Generated by Django 4.0.1 on 2022-08-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='details',
            field=models.CharField(default='DETAILS', max_length=200),
        ),
    ]
