# Generated by Django 4.0.1 on 2022-09-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=200)),
                ('description', models.CharField(default='title', max_length=200)),
            ],
        ),
    ]
