# Generated by Django 4.0.1 on 2022-09-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('link', models.CharField(default='#', max_length=200)),
            ],
        ),
    ]
