# Generated by Django 4.0.1 on 2022-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_story_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='#', max_length=200)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='message',
            field=models.TextField(default='#'),
        ),
    ]
